app:
  message: "Hello from Consumer V1"
  version: "1.0.0"

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: busrefresh,health,info,refresh
